name: recipe_app
description: "The first app prioritises recipes getting cooked, not just saved."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.1
  firebase_analytics: ^12.1.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.7
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
