name: recipe_app
description: "The first app prioritises recipes getting cooked, not just saved."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.1
  firebase_analytics: ^12.1.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_storage: ^13.0.5
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.15.0
  google_nav_bar: ^5.0.7
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  purchases_flutter: ^9.10.6
  purchases_ui_flutter: ^9.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Antique
      fonts:
        - asset: assets/antique/antiqueregular.otf
    - family: YoungSerif
      fonts:
        - asset: assets/youngserif/YoungSerif-Light.otf
          weight: 100
        - asset: assets/youngserif/YoungSerif-LightItalic.otf
          weight: 100
          style: italic
        - asset: assets/youngserif/YoungSerif-Regular.otf
          weight: 300
        - asset: assets/youngserif/YoungSerif-RegularItalic.otf
          weight: 300
          style: italic
        - asset: assets/youngserif/YoungSerif-Medium.otf
          weight: 500
        - asset: assets/youngserif/YoungSerif-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/youngserif/YoungSerif-Bold.otf
          weight: 700
        - asset: assets/youngserif/YoungSerif-BoldItalic.otf
          weight: 700
          style: italic

  assets:
    - assets/logo.png
